from utils import random_stat, team_stat, player_stat, mention_parser, get_players

# print(team_stat("bears", True, 2006, "touchdown"))
# print(team_stat("bears", False, 2006, "touchdown"))
# print(team_stat("cowboys", True, 2006, "touchdown"))
# print(team_stat("cowboys", False, 2006, "touchdown"))

# print(team_stat("bears", True, None, "xyac_epa"))
# print(team_stat("bears", True, 2020, None))
# print(team_stat("ravens", True, 2020, None)) 
# print(team_stat("bears", False, 2020, None))
# print(team_stat("ravens", True, 2020, "tot_yards"))
# print(team_stat("ravens", False, 2020, "tot_yards"))
# print(team_stat("ravens", True, 2020, "cmp_pct"))
# print(team_stat("ravens", False, 2020, "cmp_pct"))
# print(team_stat("ravens", True, 2020, "kick_distance"))

# print(player_stat("lamar jackson", 2020, "tot_yards"))
# print(player_stat("aaron donald", 2020, "tot_yards")) 
# print(player_stat("lamar jackson", 2018, "cmp_pct"))
# print(player_stat("lamar jackson", 2019, "cmp_pct"))
# print(player_stat("lamar jackson", 2020, "cmp_pct"))
# print(player_stat("lamar jackson", 2010, "passing_yards"))
# print(player_stat("marlon humphrey", 2020, "fumble_forced"))
# print(player_stat("chase claypool", 2010, "pass_touchdown"))
# print(player_stat("chase claypool", 2020, "touchdown"))
# print(player_stat("aaron rodgers", 2020, "passing_yards"))
# print(player_stat("deshaun watson", 2018, "receiving_yards"))
# print(player_stat("aaron donald", 2020, "cmp_pct")) 
# print(player_stat("marquise brown", 2020, "receiving_yards"))
# print(player_stat("josh allen", 2020, "passing yards"))
# print(player_stat("sam koch", None, "cmp_pct"))
# print(player_stat("tom brady", 2020, "touchdown")) 
# print(player_stat("tua tagovailoa", 2020, "touchdown")) 
# print(player_stat("tom brady", 2020, "interception")) 
# print(player_stat("tua tagovailoa", 2020, "interception")) 
# print(player_stat("lamar jackson", 2020, "touchdown"))
# print(player_stat("doug baldwin", 2017, "qb hit"))
# print(player_stat("marlon humphrey", 2020, "qb hit"))
# print(player_stat("lamar jackson", 2020, "qb hit"))
# print(player_stat("doug baldwin", 2017, "tackle"))
# print(player_stat("marlon humphrey", 2020, "tackle"))
# print(player_stat("lamar jackson", 2020, "tackle"))
# print(player_stat("doug baldwin", 2017, "sack"))
# print(player_stat("marlon humphrey", 2020, "sack"))
# print(player_stat("lamar jackson", 2020, "sack"))
# print(player_stat("lamar jackson", 2010, "sack"))
# print(player_stat("lamar jackson", 2010, "qb hit"))
# print(player_stat("josh allen", 2020, "qb hit"))
# print(player_stat("aaron donald", 2020, "qb hit"))
# print(player_stat("russell wilson", 2020, "qb hit"))
# print(player_stat("russell wilson", 1999, "qb hit"))
# print(mention_parser("@nfl_statsbot epa/play, Tim Hightower, 2010."))
# print(mention_parser("@nfl_statsbot epa, lamar jackson, 2019"))
# print(mention_parser("@nfl_statsbot xyac epa/play, josh allen, 2020."))
# print(mention_parser("@nfl_statsbot qb epa/play, tom brady, 2013."))
# print(mention_parser("@nfl_statsbot air epa/play, Aaron Rodgers, 2018."))
# print(mention_parser("@nfl_statsbot xyac epa, josh allen, 2020."))
# print(mention_parser("@nfl_statsbot qb epa, tom brady, 2013."))
# print(mention_parser("@nfl_statsbot air epa, Aaron Rodgers, 2018."))
# print(mention_parser("@nfl_statsbot detroit lions, epa/play allowed, 2008"))
# print(team_stat("lions", False, 2008, "epa/play"))
# print(player_stat("kurt vollers", 2004, "sack"))
# print(player_stat("kurt vollers", 2004, "tackle"))
# print(player_stat("kurt vollers", 2004, "qb_hit"))
# print(get_players(None))
print(team_stat("texans", False, 1999, "rush"))
