import sys
import time

sys.path.append('src/utils')
from stats import player_stat, random_stat, team_stat
from parsers import mention_parser, tweet_parser
from player_details import get_player_details, is_active

f = open("tests/snapshots/snapshot-" + str(time.time()) + ".txt", "w")

print("Running Team Integration Tests")
f.write(team_stat("bears", True, 2006, "touchdown")) # had 44
f.write(team_stat("bears", False, 2006, "touchdown")) # allowed 32
f.write(team_stat("cowboys", True, 2006, "touchdown")) # 
f.write(team_stat("cowboys", False, 2006, "touchdown"))
f.write(team_stat("bears", True, None, "xyac_epa"))
f.write(team_stat("patriots", True, None, None))
f.write(team_stat("patriots", False, None, None))
f.write(team_stat("patriots", True, None, "fumble"))
f.write(team_stat("patriots", False, None, "fumble"))
f.write(team_stat("bears", True, 2020, None))
f.write(team_stat("ravens", True, 2020, None)) 
f.write(team_stat("bears", False, 2020, None))
f.write(team_stat("ravens", True, 2020, "tot_yards"))
f.write(team_stat("ravens", False, 2020, "tot_yards"))
f.write(team_stat("ravens", True, 2020, "cmp_pct"))
f.write(team_stat("ravens", False, 2020, "cmp_pct"))
f.write(team_stat("ravens", True, 2020, "kick_distance"))
f.write(team_stat("ravens", False, 2020, "interception"))
f.write(team_stat("ravens", True, 2020, "interception"))
f.write(team_stat("ravens", False, 2020, "fumble"))
f.write(team_stat("ravens", True, 2020, "fumble"))
f.write(team_stat("ravens", False, 2020, "fumble_forced"))
f.write(team_stat("ravens", True, 2020, "fumble_forced"))
f.write(team_stat("ravens", False, 2020, "passing_yards"))
f.write(team_stat("ravens", True, 2020, "passing_yards"))
f.write(team_stat("lions", False, 2008, "epa/play"))
f.write(team_stat("texans", False, 1999, "rush"))

print("Running Player Integration Tests")
f.write(player_stat("lamar jackson", 2020, "tot_yards"))
f.write(player_stat("aaron donald", 2020, "tot_yards")) 
f.write(player_stat("lamar jackson", 2018, "cmp_pct"))
f.write(player_stat("lamar jackson", 2019, "cmp_pct"))
f.write(player_stat("lamar jackson", 2020, "cmp_pct"))
f.write(player_stat("lamar jackson", 2010, "passing_yards"))
f.write(player_stat("marlon humphrey", 2020, "fumble_forced"))
f.write(player_stat("chase claypool", 2010, "pass_touchdown"))
f.write(player_stat("chase claypool", 2020, "touchdown"))
f.write(player_stat("aaron rodgers", 2020, "passing_yards"))
f.write(player_stat("deshaun watson", 2018, "receiving_yards"))
f.write(player_stat("aaron donald", 2020, "cmp_pct")) 
f.write(player_stat("marquise brown", 2020, "receiving_yards"))
f.write(player_stat("josh allen", 2020, "passing yards"))
f.write(player_stat("sam koch", None, "cmp_pct"))
f.write(player_stat("tom brady", 2020, "touchdown")) 
f.write(player_stat("tua tagovailoa", 2020, "touchdown")) 
f.write(player_stat("tom brady", 2020, "interception")) 
f.write(player_stat("tua tagovailoa", 2020, "interception")) 
f.write(player_stat("lamar jackson", 2020, "touchdown"))
f.write(player_stat("doug baldwin", 2017, "qb hit"))
f.write(player_stat("marlon humphrey", 2020, "qb hit"))
f.write(player_stat("lamar jackson", 2020, "qb hit"))
f.write(player_stat("doug baldwin", 2017, "tackle"))
f.write(player_stat("marlon humphrey", 2020, "tackle"))
f.write(player_stat("lamar jackson", 2020, "tackle"))
f.write(player_stat("doug baldwin", 2017, "sack"))
f.write(player_stat("marlon humphrey", 2020, "sack"))
f.write(player_stat("lamar jackson", 2020, "sack"))
f.write(player_stat("lamar jackson", 2010, "sack"))
f.write(player_stat("lamar jackson", 2010, "qb hit"))
f.write(player_stat("josh allen", 2020, "qb hit"))
f.write(player_stat("aaron donald", 2020, "qb hit"))
f.write(player_stat("russell wilson", 2020, "qb hit"))
f.write(player_stat("russell wilson", 1999, "qb hit"))
f.write(player_stat("kurt vollers", 2004, "sack"))
f.write(player_stat("kurt vollers", 2004, "tackle"))
f.write(player_stat("kurt vollers", 2004, "qb_hit"))
f.write(player_stat("fred warner", 2020, "qb_hit"))
f.write(player_stat("fred warner", 2020, "fumble"))
f.write(player_stat("fred warner", 2020, "fumble_forced"))
f.write(player_stat("lamar jackson", 2019, "fumble"))
f.write(player_stat("kyler murray", 2019, "fumble_forced"))
f.write(player_stat("julio jones", None, "interception"))
f.write(player_stat("julio jones", 2020, "fumble"))
f.write(player_stat("lamar jackson", None, "interception"))
f.write(player_stat("tom brady", 2004, "rushing_yards"))
f.write(player_stat("marlon humphrey", 2019, "rushing_yards"))
f.write(player_stat("luke kuechly", 2016, "sack"))
f.write(player_stat("luke kuechly", 2016, "assist_tackle"))
f.write(player_stat("ronnie stanley", 2019, "penalty"))
f.write(player_stat("ronnie stanley", 2018, "penalty_yards"))
f.write(player_stat("lamar jackson", 2018, "fourth_down_converted", "qb"))
f.write(player_stat("lamar jackson", 2018, "fourth_down_converted"))
f.write(player_stat("lamar jackson", 2018, "fourth_down_converted", "db"))
f.write(player_stat("lamar jackson", 2018, "first_down_penalty", None))
f.write(player_stat("sam koch", 2018, "cpoe"))
f.write(player_stat("saquon barkley", 2018, "cpoe"))
f.write(player_stat("marlon humphrey", 2018, "cpoe"))
f.write(player_stat("brandon williams", 2018, "cpoe"))
f.write(player_stat("mohamed sanu", 2018, "pass_attempt"))
f.write(player_stat("jarvis landry", 2020, "incomplete_pass"))
f.write(player_stat("tom brady", 2020, "reception"))
f.write(player_stat("tarik cohen", 2019, "tot_yards"))
f.write(player_stat("deshon elliott", 2020, "fumble_forced"))
f.write(player_stat("tarik cohen", 2019, "fumble_forced"))
f.write(player_stat("russell wilson", 2020, "sack"))
f.write(player_stat("jayson oweh", 2020, "sack"))
f.write(player_stat("jayson oweh", 2021, "sack"))
f.write(player_stat("rondale moore", 2021, "receiving yards"))
f.write(player_stat("jayson oweh", None, "sack"))
f.write(player_stat("josh allen", 2020, "passing yards"))
f.write(player_stat("lamar jackson", 2021, "rushing yards", "QB"))
f.write(player_stat("kadarius toney", 2021, "receiving yards"))
f.write(player_stat("trevon diggs", 2021, "temperature"))
f.write(player_stat("josh allenkjkb", 2010, "sack"))

print("Running Player Details Integration Tests")
f.write(get_player_details("lamar jackson", 2020, "qb"))
f.write(get_player_details("lamar jackson", 2020, "db"))
f.write(get_player_details("lamar jackson", 2020, None))
f.write(get_player_details("lamar jackson", 2020, None))
f.write(get_player_details("lamar jackson", 2020, None))
f.write(get_player_details("lamar jackson", 2020, "wr"))
f.write(get_player_details("lamar jackson", 2020, None))
f.write(get_player_details("tom brady", 2004, None))

print("Running Mention Parser Integration Tests")
f.write(mention_parser("josh allen, passing yards, 2019, 2020"))
f.write(mention_parser("@nfl_statsbot Stephon Gillmore, Interceptions, 2019"))
f.write(mention_parser(".@nfl_statsbot Stephon Gillmore, Interceptions, 2019"))
f.write(mention_parser("@nfl_statsbot epa/play, Tim Hightower, lamar jackson, 2010."))
f.write(mention_parser("@nfl_statsbot epa, lamar jackson(db), josh allen (qb), 2019"))
f.write(mention_parser("@nfl_statsbot xyac epa/play, josh allen, 2020."))
f.write(mention_parser("@nfl_statsbot qb epa/play, tom brady, 2013."))
f.write(mention_parser("@nfl_statsbot air epa/play, Aaron Rodgers, 2018."))
f.write(mention_parser("@nfl_statsbot xyac epa, josh allen, 2020."))
f.write(mention_parser("@nfl_statsbot qb epa, tom brady, 2013."))
f.write(mention_parser("@nfl_statsbot air epa, Aaron Rodgers, 2018."))
f.write(mention_parser("@nfl_statsbot detroit lions, epa/play allowed, 2008"))
f.write(mention_parser("@nfl_statsbot lamar jackson (qb), epa/play, 2020"))
f.write(mention_parser("@nfl_statsbot lamar jackson (db), epa/play, 2020"))
f.write(mention_parser("@nfl_statsbot josh allen (qb), epa/play, 2020"))

print("Running Is Active Integration Tests")
f.write(is_active('00-0036940', None))

f.close()

# f.write(get_roster_data(2022).head())