import sys
import time

sys.path.append('src/utils')
from stats import player_stat, random_stat, team_stat
from parsers import mention_parser, tweet_parser
from player_details import get_player_details, is_active

f = open("tests/snapshots/snapshot-" + str(time.time()) + ".txt", "w")

print("Running Team Integration Tests")
f.write(team_stat("bears", True, 2006, "touchdown") + "\n") # had 44
f.write(team_stat("bears", False, 2006, "touchdown") + "\n") # allowed 32
f.write(team_stat("cowboys", True, 2006, "touchdown") + "\n") # 
f.write(team_stat("cowboys", False, 2006, "touchdown") + "\n")
f.write(team_stat("bears", True, None, "xyac_epa") + "\n")
f.write(team_stat("patriots", True, None, None) + "\n")
f.write(team_stat("patriots", False, None, None) + "\n")
f.write(team_stat("patriots", True, None, "fumble") + "\n")
f.write(team_stat("patriots", False, None, "fumble") + "\n")
f.write(team_stat("bears", True, 2020, None) + "\n")
f.write(team_stat("ravens", True, 2020, None) + "\n") 
f.write(team_stat("bears", False, 2020, None) + "\n")
f.write(team_stat("ravens", True, 2020, "tot_yards") + "\n")
f.write(team_stat("ravens", False, 2020, "tot_yards") + "\n")
f.write(team_stat("ravens", True, 2020, "cmp_pct") + "\n")
f.write(team_stat("ravens", False, 2020, "cmp_pct") + "\n")
f.write(team_stat("ravens", True, 2020, "kick_distance") + "\n")
f.write(team_stat("ravens", False, 2020, "interception") + "\n")
f.write(team_stat("ravens", True, 2020, "interception") + "\n")
f.write(team_stat("ravens", False, 2020, "fumble") + "\n")
f.write(team_stat("ravens", True, 2020, "fumble") + "\n")
f.write(team_stat("ravens", False, 2020, "fumble_forced") + "\n")
f.write(team_stat("ravens", True, 2020, "fumble_forced") + "\n")
f.write(team_stat("ravens", False, 2020, "passing_yards") + "\n")
f.write(team_stat("ravens", True, 2020, "passing_yards") + "\n")
f.write(team_stat("lions", False, 2008, "epa/play") + "\n")
f.write(team_stat("texans", False, 1999, "rush") + "\n")

print("Running Player Integration Tests")
f.write(player_stat("lamar jackson", 2020, "tot_yards") + "\n")
f.write(player_stat("aaron donald", 2020, "tot_yards") + "\n") 
f.write(player_stat("lamar jackson", 2018, "cmp_pct") + "\n")
f.write(player_stat("lamar jackson", 2019, "cmp_pct") + "\n")
f.write(player_stat("lamar jackson", 2020, "cmp_pct") + "\n")
f.write(player_stat("lamar jackson", 2010, "passing_yards") + "\n")
f.write(player_stat("marlon humphrey", 2020, "fumble_forced") + "\n")
f.write(player_stat("chase claypool", 2010, "pass_touchdown") + "\n")
f.write(player_stat("chase claypool", 2020, "touchdown") + "\n")
f.write(player_stat("aaron rodgers", 2020, "passing_yards") + "\n")
f.write(player_stat("deshaun watson", 2018, "receiving_yards") + "\n")
f.write(player_stat("aaron donald", 2020, "cmp_pct") + "\n") 
f.write(player_stat("marquise brown", 2020, "receiving_yards") + "\n")
f.write(player_stat("josh allen", 2020, "passing yards") + "\n")
f.write(player_stat("sam koch", None, "cmp_pct") + "\n")
f.write(player_stat("tom brady", 2020, "touchdown") + "\n") 
f.write(player_stat("tua tagovailoa", 2020, "touchdown") + "\n") 
f.write(player_stat("tom brady", 2020, "interception") + "\n") 
f.write(player_stat("tua tagovailoa", 2020, "interception") + "\n") 
f.write(player_stat("lamar jackson", 2020, "touchdown") + "\n")
f.write(player_stat("doug baldwin", 2017, "qb hit") + "\n")
f.write(player_stat("marlon humphrey", 2020, "qb hit") + "\n")
f.write(player_stat("lamar jackson", 2020, "qb hit") + "\n")
f.write(player_stat("doug baldwin", 2017, "tackle") + "\n")
f.write(player_stat("marlon humphrey", 2020, "tackle") + "\n")
f.write(player_stat("lamar jackson", 2020, "tackle") + "\n")
f.write(player_stat("doug baldwin", 2017, "sack") + "\n")
f.write(player_stat("marlon humphrey", 2020, "sack") + "\n")
f.write(player_stat("lamar jackson", 2020, "sack") + "\n")
f.write(player_stat("lamar jackson", 2010, "sack") + "\n")
f.write(player_stat("lamar jackson", 2010, "qb hit") + "\n")
f.write(player_stat("josh allen", 2020, "qb hit") + "\n")
f.write(player_stat("aaron donald", 2020, "qb hit") + "\n")
f.write(player_stat("russell wilson", 2020, "qb hit") + "\n")
f.write(player_stat("russell wilson", 1999, "qb hit") + "\n")
f.write(player_stat("kurt vollers", 2004, "sack") + "\n")
f.write(player_stat("kurt vollers", 2004, "tackle") + "\n")
f.write(player_stat("kurt vollers", 2004, "qb_hit") + "\n")
f.write(player_stat("fred warner", 2020, "qb_hit") + "\n")
f.write(player_stat("fred warner", 2020, "fumble") + "\n")
f.write(player_stat("fred warner", 2020, "fumble_forced") + "\n")
f.write(player_stat("lamar jackson", 2019, "fumble") + "\n")
f.write(player_stat("kyler murray", 2019, "fumble_forced") + "\n")
f.write(player_stat("julio jones", None, "interception") + "\n")
f.write(player_stat("julio jones", 2020, "fumble") + "\n")
f.write(player_stat("lamar jackson", None, "interception") + "\n")
f.write(player_stat("tom brady", 2004, "rushing_yards") + "\n")
f.write(player_stat("marlon humphrey", 2019, "rushing_yards") + "\n")
f.write(player_stat("luke kuechly", 2016, "sack") + "\n")
f.write(player_stat("luke kuechly", 2016, "assist_tackle") + "\n")
f.write(player_stat("ronnie stanley", 2019, "penalty") + "\n")
f.write(player_stat("ronnie stanley", 2018, "penalty_yards") + "\n")
f.write(player_stat("lamar jackson", 2018, "fourth_down_converted", "qb") + "\n")
f.write(player_stat("lamar jackson", 2018, "fourth_down_converted") + "\n")
f.write(player_stat("lamar jackson", 2018, "fourth_down_converted", "db") + "\n")
f.write(player_stat("lamar jackson", 2018, "first_down_penalty", None) + "\n")
f.write(player_stat("sam koch", 2018, "cpoe") + "\n")
f.write(player_stat("saquon barkley", 2018, "cpoe") + "\n")
f.write(player_stat("marlon humphrey", 2018, "cpoe") + "\n")
f.write(player_stat("brandon williams", 2018, "cpoe") + "\n")
f.write(player_stat("mohamed sanu", 2018, "pass_attempt") + "\n")
f.write(player_stat("jarvis landry", 2020, "incomplete_pass") + "\n")
f.write(player_stat("tom brady", 2020, "reception") + "\n")
f.write(player_stat("tarik cohen", 2019, "tot_yards") + "\n")
f.write(player_stat("deshon elliott", 2020, "fumble_forced") + "\n")
f.write(player_stat("tarik cohen", 2019, "fumble_forced") + "\n")
f.write(player_stat("russell wilson", 2020, "sack") + "\n")
f.write(player_stat("jayson oweh", 2020, "sack") + "\n")
f.write(player_stat("jayson oweh", 2021, "sack") + "\n")
f.write(player_stat("rondale moore", 2021, "receiving yards") + "\n")
f.write(player_stat("jayson oweh", None, "sack") + "\n")
f.write(player_stat("josh allen", 2020, "passing yards") + "\n")
f.write(player_stat("lamar jackson", 2021, "rushing yards", "QB") + "\n")
f.write(player_stat("kadarius toney", 2021, "receiving yards") + "\n")
f.write(player_stat("trevon diggs", 2021, "temperature") + "\n")
f.write(player_stat("josh allenkjkb", 2010, "sack") + "\n")

print("Running Player Details Integration Tests")
f.write(str(get_player_details("lamar jackson", 2020, "qb")) + "\n")
f.write(str(get_player_details("lamar jackson", 2020, "db")) + "\n")
f.write(str(get_player_details("lamar jackson", 2020, None)) + "\n")
f.write(str(get_player_details("lamar jackson", 2020, None)) + "\n")
f.write(str(get_player_details("lamar jackson", 2020, None)) + "\n")
f.write(str(get_player_details("lamar jackson", 2020, "wr")) + "\n")
f.write(str(get_player_details("lamar jackson", 2020, None)) + "\n")
f.write(str(get_player_details("tom brady", 2004, None)) + "\n")

print("Running Mention Parser Integration Tests")
f.write(mention_parser("josh allen, passing yards, 2019, 2020") + "\n")
f.write(mention_parser("@nfl_statsbot Stephon Gillmore, Interceptions, 2019") + "\n")
f.write(mention_parser(".@nfl_statsbot Stephon Gillmore, Interceptions, 2019") + "\n")
f.write(mention_parser("@nfl_statsbot epa/play, Tim Hightower, lamar jackson, 2010.") + "\n")
f.write(mention_parser("@nfl_statsbot epa, lamar jackson(db), josh allen (qb), 2019") + "\n")
f.write(mention_parser("@nfl_statsbot xyac epa/play, josh allen, 2020.") + "\n")
f.write(mention_parser("@nfl_statsbot qb epa/play, tom brady, 2013.") + "\n")
f.write(mention_parser("@nfl_statsbot air epa/play, Aaron Rodgers, 2018.") + "\n")
f.write(mention_parser("@nfl_statsbot xyac epa, josh allen, 2020.") + "\n")
f.write(mention_parser("@nfl_statsbot qb epa, tom brady, 2013.") + "\n")
f.write(mention_parser("@nfl_statsbot air epa, Aaron Rodgers, 2018.") + "\n")
f.write(mention_parser("@nfl_statsbot detroit lions, epa/play allowed, 2008") + "\n")
f.write(mention_parser("@nfl_statsbot lamar jackson (qb), epa/play, 2020") + "\n")
f.write(mention_parser("@nfl_statsbot lamar jackson (db), epa/play, 2020") + "\n")
f.write(mention_parser("@nfl_statsbot josh allen (qb), epa/play, 2020") + "\n")

print("Running Is Active Integration Tests")
f.write(is_active('00-0036940', None) + "\n")

f.close()

# f.write(get_roster_data(2022).head() + "\n")